# Generated by Django 3.0.6 on 2020-10-27 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_breed_dog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dog',
            options={'ordering': ['id']},
        ),
    ]
