# Generated by Django 3.0.6 on 2020-10-27 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20201027_0529'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='breed',
            options={'ordering': ['id']},
        ),
    ]
