# Generated by Django 3.0.6 on 2020-10-27 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20201027_0530'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dog',
            options={},
        ),
    ]
