# Generated by Django 3.0.6 on 2020-10-27 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20201027_0547'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='breed',
            options={},
        ),
    ]
